apiVersion: v1
kind: ConfigMap
metadata:
  name: notify-gateway-config
  namespace: notify-hub
data:
  DB_HOST: "mysql.notify-hub.svc.cluster.local"
  DB_PORT: "3306"
  DB_NAME: "notify_hub"
  REDIS_HOST: "redis.notify-hub.svc.cluster.local"
  REDIS_PORT: "6379"
  SERVER_PORT: "8080"
  LOG_LEVEL: "INFO"
  
  # JVM 配置
  JAVA_OPTS: >-
    -Xms512m
    -Xmx512m
    -XX:+UseG1GC
    -XX:MaxGCPauseMillis=200
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:HeapDumpPath=/logs/heapdump.hprof
